# Generated by Django 2.1.1 on 2018-09-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('world', 'World'), ('technology', 'Technology'), ('culture', 'Culture')], default='world', max_length=10),
        ),
    ]
