# Generated by Django 2.1.1 on 2018-10-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_remove_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpicture',
            name='postid',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='PostPicture',
        ),
    ]
