# Generated by Django 2.1.1 on 2018-10-29 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0009_auto_20181029_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
