# Generated by Django 2.1.1 on 2018-11-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0012_auto_20181029_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='posts/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=250, unique_for_date='publish'),
        ),
    ]
