# Generated by Django 2.1.1 on 2018-11-18 07:13

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0017_auto_20181118_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('world', 'World'), ('technology', 'Technology'), ('culture', 'Culture')], default='world', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categiry', to='Post.Category'),
        ),
    ]
