# Generated by Django 2.1.1 on 2018-11-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0018_auto_20181118_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('world', 'World'), ('technology', 'Technology'), ('culture', 'Culture'), ('design', 'Design'), ('business', 'Business'), ('politic', 'Politic'), ('opinion', 'Opinion'), ('health', 'Health'), ('travel', 'Travel')], default='world', max_length=10),
        ),
    ]
